name: 'NPM Publish'
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn remove @vue/composition-api
      - run: yarn add --peer @vue/composition-api
      - run: yarn version
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}